### PR TITLE
Tab content flexbox improvements

### PR DESCRIPTION
**Pull request by rafaelmardojai**

### CODE REVIEW

**Comment by lunakurame** [comment]
Next time add at least a short description what does your pull request change, it took me a while to find any changes in behavior.

Looks like if you mute a tab, the mute icon teleports next to the label after a random time (~3 seconds), your changes fix that issue, thanks!

**Comment by lunakurame** [comment]
Do you know what is `.tabbrowser-tab[bussy]` for? You added it in #16 and now you changed `[bussy]` to `[busy]`, but not in all places, so we have both. I can't find any tabs with this attribute.

**Comment by rafaelmardojai** [comment]
That was an error, by mistake I added an extra  "s" to "busy".

**Comment by lunakurame** [comment]
Oh, okay then, I'll change the rest of `bussy` to `busy`. But what is this selector for? I can't find any tabs with the `busy` attribute.

**Comment by rafaelmardojai** [comment]
The `busy` attribute is similar to `progress`.
When you load a new tab from a link, that tab usually get the `busy` attr. Or when you start Firefox, the homepage tab have the `busy` attr too.

Edit: but this attribute disappears quickly.

**Comment by lunakurame** [comment]
Okay, makes sense. Thanks for clarifying.

**Pull request merged**
