### PR TITLE
Fix blurred tab close icon on FF61

### PR DESCRIPTION
**Pull request by rafaelmardojai**
I don't know if this break something on previous FF versions.

### CODE REVIEW

**Comment by lunakurame** [comment]
Looks nice, thanks! This bug is in FF 59 too, but not FF 58. I'll merge this pull request tomorrow, because I'll be ending FF 58 support. Also your fix makes the whole button smaller - the button's border is too small.

Firefox 58:
image

Firefox 59+ with your fix:
image

But it's easy to fix, so that's okay.
```css
.tab-close-button {
	padding: 2px;
	margin-left: 1px;
}
```

**Comment by rafaelmardojai** [comment]
Oh, i don't noticed that padding xD thanks.

BTW,  i was thinking that we should add the `--gnome-icons-hack-close-button-hover-bgimage` and `--gnome-icons-hack-close-button-hover-box-shadow` variables to the themes, for better GTK look.

**Comment by lunakurame** [comment]
Merged your commits.

About those two new variables: if they are needed, then sure, we could add them. But are they needed? Everything looks fine to me on GNOME 3.18, I don't know about other versions.

**Comment by rafaelmardojai** [comment]
This is FF close tab button on hover (looks flat):
captura de pantalla de 2018-04-02 10-44-47

And this is GTK+ app close tab button on hover (3.26):
captura de pantalla de 2018-04-02 10-45-24

**Comment by lunakurame** [comment]
You're right. I added those two new variables and set them both to `none`. Now you can give them proper values for the 3.26 theme variants (I can't do it since I don't use 3.26).

**Pull request merged**
